name: 🚀 Alpha Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"

jobs:
  cargo:
    needs: ["github-release"]
    uses: xsv24/inkan/.github/workflows/cargo-publish.yml@main
    with:
      version: ${{ github.ref_name }}
      dry-run: false
